name: Test React App
on: push
jobs:
  test_my_app:
    runs-on: ubuntu_latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Test application
        run: npm run test
      

