name: Deploy React App
on: push
jobs:
  test_my_app:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test application
        run: npm run test
  lint_my_app:
    runs-on: ubuntu-latest
    needs: test_my_app
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: lint application
        run: npm run lint
  build_my_app:
    runs-on: ubuntu-latest
    needs: lint_my_app
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: build application
        run: npm run build
      - name: Deploy
        run: echo Deploying..

      

